<?php

namespace AppBundle\Repository;

/**
 * Utilisateurs1Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Utilisateurs1Repository extends \Doctrine\ORM\EntityRepository
{
}
