AppBundle\Entity\Places:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: name
    properties:
        name:
            - NotBlank: ~
            - Type: string
        address:
            - NotBlank: ~
            - Type: string

AppBundle\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: email
    properties:
        firstname:
            - NotBlank: ~
            - Type: string
        lastname:
            - NotBlank: ~
            - Type: string
        email:
            - NotBlank: ~
            - Email: ~

AppBundle\Entity\Boisson:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: nom
    properties:
        nom:
            - NotBlank: ~
            - Type: string
        pm:
            - NotBlank: ~
            - Type: string
        gm:
            - NotBlank: ~
            - Type: string

AppBundle\Entity\Pizza:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: nom
    properties:
        nom:
            - NotBlank: ~
            - Type: string
        pm:
            - NotBlank: ~
            - Type: string
        gm:
            - NotBlank: ~
            - Type: string
        ingredient:
            - NotBlank: ~
            - Type: string            